title: Welcome to jieun blog
description: hello
bseurl: "" # the subpath of your site, e.g. /blog
url: "jieunid.github.io/jieun" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    kangjieun
author-image:   jieun.jpg
author-job:     Web Developer, Designer
author-email:   wldms87985@naver.com # Add your email for contant form.
author-twitter:  kangjieun555 # Add your twitter account
about-author:   디자인 가능한 웹 퍼블리셔 & 웹프론트앤드 

# Site Author
#author:
 # avatar           : "/assets/images/jieun.jpg"
  #bio              : "웹디자인 가능한 웹퍼브리셔 & 웹 프론트앤드개발"
 # location         : "South Korea"
 # email            :
 # links:
   # - label: "Email"
   #   icon: "fas fa-fw fa-envelope-square"
   #   url: mailto:devinlifeidea@gmail.com
   # - label: "Website"
   #   icon: "fas fa-fw fa-link"
    #  url: "https://jieunid.github.io/jieun/"




# Social settings
social-twitter:  kangjieun555
social-facebook:
social-github:   jieunid/jieun
social-pinterest: 
social-instagram: kangjieun555
social-youtube:
social-vk:   
social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # 블로그 댓글 기능 true
      share: true
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: false

      # Analytics
analytics:
  provider               : false # 구글 어날리틱스 등록 false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)

# Disqus
disqus: True
disqus_shortname: xxxxxxxx
# disqus는 온라인 댓글 시스템. 댓글 기능을 사용하기 위해
# disqus를 이용할 것인지 여부와 만약 사용하면
# disqus shortname을 입력 ( disqus username이 아님 )
theme: jekyll-theme-cayman